version: '3'

volumes:
  db:

services:
  symfony:
    build:
      context: ./symfony
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    environment:
      APP_ENV: dev

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./react/dist/:/usr/share/nginx/html
    ports:
      - "82:80"
    environment:
      HOSTNAME_INTERNAL_PHP: symfony:9000
      HOSTNAME_PUBLIC_BACKEND: localhost:9000
      HOSTNAME_INTERNAL_NGINX: nginx